##服务端口
#server:
#  port: 8002
#  #服务名
#spring:
#  # nacos服务地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 175.178.189.89:12208
#  application:
#    name: service-oss
#    #环境设置：dev、test、prod
#  profiles:
#    active: dev
#
#  servlet:
#    multipart:
#      max-file-size: 3MB #单个文件大小
#      max-request-size: 10MB #请求总文件大小
#
#    #阿里云 OSS
#    #不同的服务器，地址不同
#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-chengdu.aliyuncs.com
#      keyid: LTAI5tRSKa9N5nQ24CsqBT6N
#      keysecret: ce3fnHWleFRWm9Wl921Admy1ZxL9Ei
#      #bucket可以在控制台创建，也可以使用java代码创建
#      bucketname: edu-mogu
#
#
#
